// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEv-R-ldgNqPRe9bISG8ldIx3ntbKl7ok',
    appId: '1:541058254186:web:496b6b3ad3b1cd99cf5113',
    messagingSenderId: '541058254186',
    projectId: 'datapump-9d6d8',
    authDomain: 'datapump-9d6d8.firebaseapp.com',
    databaseURL: 'https://datapump-9d6d8-default-rtdb.firebaseio.com',
    storageBucket: 'datapump-9d6d8.appspot.com',
    measurementId: 'G-JPY9TZZ5LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ-o_vS5lMzt0RRUl64DbekoIpvK-l4Iw',
    appId: '1:541058254186:android:65a8fefaa1c39b76cf5113',
    messagingSenderId: '541058254186',
    projectId: 'datapump-9d6d8',
    databaseURL: 'https://datapump-9d6d8-default-rtdb.firebaseio.com',
    storageBucket: 'datapump-9d6d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABneAx-3_PeIMYNWUIrhAx5LEp8dWl_ug',
    appId: '1:541058254186:ios:9fb4762f56d8e529cf5113',
    messagingSenderId: '541058254186',
    projectId: 'datapump-9d6d8',
    databaseURL: 'https://datapump-9d6d8-default-rtdb.firebaseio.com',
    storageBucket: 'datapump-9d6d8.appspot.com',
    androidClientId: '541058254186-87njipc0qfso5fbn6kuruqjgjqa6hltf.apps.googleusercontent.com',
    iosClientId: '541058254186-j4787rjaa4mht1vfrs7thgscencksik6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABneAx-3_PeIMYNWUIrhAx5LEp8dWl_ug',
    appId: '1:541058254186:ios:9fb4762f56d8e529cf5113',
    messagingSenderId: '541058254186',
    projectId: 'datapump-9d6d8',
    databaseURL: 'https://datapump-9d6d8-default-rtdb.firebaseio.com',
    storageBucket: 'datapump-9d6d8.appspot.com',
    androidClientId: '541058254186-87njipc0qfso5fbn6kuruqjgjqa6hltf.apps.googleusercontent.com',
    iosClientId: '541058254186-j4787rjaa4mht1vfrs7thgscencksik6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmsp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEv-R-ldgNqPRe9bISG8ldIx3ntbKl7ok',
    appId: '1:541058254186:web:7a79d7fe0c861f79cf5113',
    messagingSenderId: '541058254186',
    projectId: 'datapump-9d6d8',
    authDomain: 'datapump-9d6d8.firebaseapp.com',
    databaseURL: 'https://datapump-9d6d8-default-rtdb.firebaseio.com',
    storageBucket: 'datapump-9d6d8.appspot.com',
    measurementId: 'G-6B8JZJZ64W',
  );
}
